# Generated by Django 5.1.5 on 2025-03-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0002_ship_nickname_historicalship"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishspecies",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="historicalfishspecies",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
    ]
