# Generated by Django 5.1.5 on 2025-02-28 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0002_ingametime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingametime",
            name="start_time",
        ),
    ]
