# Generated by Django 5.1.5 on 2025-02-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0003_remove_ingametime_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingametime",
            name="start_time",
            field=models.FloatField(default=0),
        ),
    ]
