# Generated by Django 5.1.5 on 2025-02-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.FloatField(default=1000.0),
        ),
    ]
