# Generated by Django 5.1.5 on 2025-03-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0004_fishspecies_harbor_historicalfishspecies_harbor"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturerShip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fishing_capacity", models.IntegerField(default=0)),
                ("fishing_rate", models.IntegerField()),
                ("base_cost", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
