# Generated by Django 5.1.5 on 2025-02-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0004_profile_balance"),
    ]

    operations = [
        migrations.CreateModel(
            name="FishStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_fish", models.IntegerField(default=10000)),
                ("fish_value", models.FloatField(default=1.0)),
            ],
        ),
    ]
