# Generated by Django 5.1.5 on 2025-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0005_manufacturership_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0.01)),
            ],
        ),
    ]
