# Generated by Django 5.1.5 on 2025-02-12 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0006_ship_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ship",
            old_name="fish_capacity",
            new_name="fishing_rate",
        ),
    ]
