# Generated by Django 5.1.5 on 2025-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0007_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
