# Generated by Django 5.1.5 on 2025-02-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0008_remove_ship_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="ship",
            name="ship_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ship",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
