# Generated by Django 5.1.5 on 2025-03-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0009_group_historicalprofile_group_profile_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_group",
                to="fishbanksapp.group",
            ),
        ),
    ]
