# Generated by Django 5.1.5 on 2025-02-16 19:10

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0009_ship_ship_id_ship_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ship",
            name="ship_id",
        ),
        migrations.AddField(
            model_name="profile",
            name="ships_list",
            field=models.JSONField(
                default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
