# Generated by Django 5.1.5 on 2025-02-16 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0011_alter_profile_ships_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="ships_list",
        ),
    ]
