# Generated by Django 5.1.5 on 2025-03-23 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0011_group_created_at_group_members_alter_group_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprofile",
            name="group",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="group",
        ),
    ]
