# Generated by Django 5.1.5 on 2025-03-24 01:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0014_invitation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invitation",
            old_name="organization",
            new_name="group",
        ),
    ]
