# Generated by Django 5.1.5 on 2025-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0014_fishspecies_historicalfishspecies_delete_fishstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishspecies",
            name="name",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="historicalfishspecies",
            name="name",
            field=models.TextField(default=None),
        ),
    ]
