# Generated by Django 5.1.5 on 2025-02-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0016_historicalprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishspecies",
            name="C",
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name="fishspecies",
            name="k",
            field=models.FloatField(default=0.01),
        ),
        migrations.AddField(
            model_name="historicalfishspecies",
            name="C",
            field=models.FloatField(default=100000),
        ),
        migrations.AddField(
            model_name="historicalfishspecies",
            name="k",
            field=models.FloatField(default=0.01),
        ),
    ]
