# Generated by Django 5.1.5 on 2025-03-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0017_alter_transaction_reciever"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
