# Generated by Django 5.1.5 on 2025-03-31 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0018_alter_transaction_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sold", "Sold"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("buy_now_price", models.FloatField(default=0)),
                ("current_bid", models.FloatField(default=0)),
                ("starting_bid", models.FloatField(default=0)),
                ("details", models.TextField(null=True)),
                (
                    "ship",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fishbanksapp.ship",
                    ),
                ),
            ],
        ),
    ]
