# Generated by Django 5.1.5 on 2025-04-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0021_auctionlisting_current_bidder_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="ship",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listing_ship",
                to="fishbanksapp.ship",
            ),
        ),
    ]
