# Generated by Django 5.1.5 on 2025-04-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("fishbanksapp", "0023_traderequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="object_id",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
