# Generated by Django 5.1.5 on 2025-04-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0024_alter_transaction_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="fishbanksapp/static/profile_pics/"
            ),
        ),
    ]
