# Generated by Django 5.1.5 on 2025-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fishbanksapp", "0025_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturership",
            name="max_stock",
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name="manufacturership",
            name="stock",
            field=models.IntegerField(default=20),
        ),
    ]
