"""
Django settings for fishbanks project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^_dcyup5afnz2wr34a6-0bbl*!vfh$5=91smzm006583k+l52^"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['18.222.82.204', 'openfishbanks.org', 'www.openfishbanks.org', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "fishbanksapp",
    'register.apps.RegisterConfig',
    "crispy_forms",
    "crispy_bootstrap4",
    "simple_history",
    "celery",
    'django.contrib.humanize',
    'corsheaders',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = "fishbanks.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fishbanks.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "fishbanksapp/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CRISPY_TEMPLATE_PACK ="bootstrap4"

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'
LOGOUT_URL = 'logout/'

TIME_ZONE = 'America/New_York'
USE_TZ = True  # Ensure USE_TZ is True to enable timezone support


from celery.schedules import crontab

POPULATION_UPDATE_INTERVAL = '1'


CELERY_BEAT_SCHEDULE = {
    'increment-population-every-minute': {
         'task': 'fishbanksapp.tasks.update_population',
         'schedule': crontab(minute='*/{time}'.format(time=POPULATION_UPDATE_INTERVAL)),  # This runs the task every minute
    },
    'return-ships-every-30-minutes': {
         'task': 'fishbanksapp.tasks.return_ships',
         'schedule': crontab(minute='*/30'),
    },
    'close-auctions-every-30-seconds': {
         'task': 'fishbanksapp.tasks.process_ended_auctions',
         'schedule': 30.0,
    },
}

STATIC_URL = '/static/'

STATIC_ROOT = 'fishbanksapp/static/'


SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True


CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Use Redis for the broker
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'  # Use Redis for the backend
CELERY_TIMEZONE = 'UTC'

CORS_ALLOWED_ORIGINS = [
    'https://your-domain.com',  # Add your website's domain here
]